// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: google/monitoring/v3/metric_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf
import SwiftProtobuf

// MARK: - google.monitoring.v3.MetricService

/// Namespace containing generated types for the "google.monitoring.v3.MetricService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
package enum Google_Monitoring_V3_MetricService: Sendable {
    /// Service descriptor for the "google.monitoring.v3.MetricService" service.
    package static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.monitoring.v3.MetricService")
    /// Namespace for method metadata.
    package enum Method: Sendable {
        /// Namespace for "ListMonitoredResourceDescriptors" metadata.
        package enum ListMonitoredResourceDescriptors: Sendable {
            /// Request type for "ListMonitoredResourceDescriptors".
            package typealias Input = Google_Monitoring_V3_ListMonitoredResourceDescriptorsRequest
            /// Response type for "ListMonitoredResourceDescriptors".
            package typealias Output = Google_Monitoring_V3_ListMonitoredResourceDescriptorsResponse
            /// Descriptor for "ListMonitoredResourceDescriptors".
            package static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.monitoring.v3.MetricService"),
                method: "ListMonitoredResourceDescriptors",
                type: .unary
            )
        }
        /// Namespace for "GetMonitoredResourceDescriptor" metadata.
        package enum GetMonitoredResourceDescriptor: Sendable {
            /// Request type for "GetMonitoredResourceDescriptor".
            package typealias Input = Google_Monitoring_V3_GetMonitoredResourceDescriptorRequest
            /// Response type for "GetMonitoredResourceDescriptor".
            package typealias Output = Google_Api_MonitoredResourceDescriptor
            /// Descriptor for "GetMonitoredResourceDescriptor".
            package static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.monitoring.v3.MetricService"),
                method: "GetMonitoredResourceDescriptor",
                type: .unary
            )
        }
        /// Namespace for "ListMetricDescriptors" metadata.
        package enum ListMetricDescriptors: Sendable {
            /// Request type for "ListMetricDescriptors".
            package typealias Input = Google_Monitoring_V3_ListMetricDescriptorsRequest
            /// Response type for "ListMetricDescriptors".
            package typealias Output = Google_Monitoring_V3_ListMetricDescriptorsResponse
            /// Descriptor for "ListMetricDescriptors".
            package static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.monitoring.v3.MetricService"),
                method: "ListMetricDescriptors",
                type: .unary
            )
        }
        /// Namespace for "GetMetricDescriptor" metadata.
        package enum GetMetricDescriptor: Sendable {
            /// Request type for "GetMetricDescriptor".
            package typealias Input = Google_Monitoring_V3_GetMetricDescriptorRequest
            /// Response type for "GetMetricDescriptor".
            package typealias Output = Google_Api_MetricDescriptor
            /// Descriptor for "GetMetricDescriptor".
            package static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.monitoring.v3.MetricService"),
                method: "GetMetricDescriptor",
                type: .unary
            )
        }
        /// Namespace for "CreateMetricDescriptor" metadata.
        package enum CreateMetricDescriptor: Sendable {
            /// Request type for "CreateMetricDescriptor".
            package typealias Input = Google_Monitoring_V3_CreateMetricDescriptorRequest
            /// Response type for "CreateMetricDescriptor".
            package typealias Output = Google_Api_MetricDescriptor
            /// Descriptor for "CreateMetricDescriptor".
            package static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.monitoring.v3.MetricService"),
                method: "CreateMetricDescriptor",
                type: .unary
            )
        }
        /// Namespace for "DeleteMetricDescriptor" metadata.
        package enum DeleteMetricDescriptor: Sendable {
            /// Request type for "DeleteMetricDescriptor".
            package typealias Input = Google_Monitoring_V3_DeleteMetricDescriptorRequest
            /// Response type for "DeleteMetricDescriptor".
            package typealias Output = SwiftProtobuf.Google_Protobuf_Empty
            /// Descriptor for "DeleteMetricDescriptor".
            package static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.monitoring.v3.MetricService"),
                method: "DeleteMetricDescriptor",
                type: .unary
            )
        }
        /// Namespace for "ListTimeSeries" metadata.
        package enum ListTimeSeries: Sendable {
            /// Request type for "ListTimeSeries".
            package typealias Input = Google_Monitoring_V3_ListTimeSeriesRequest
            /// Response type for "ListTimeSeries".
            package typealias Output = Google_Monitoring_V3_ListTimeSeriesResponse
            /// Descriptor for "ListTimeSeries".
            package static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.monitoring.v3.MetricService"),
                method: "ListTimeSeries",
                type: .unary
            )
        }
        /// Namespace for "CreateTimeSeries" metadata.
        package enum CreateTimeSeries: Sendable {
            /// Request type for "CreateTimeSeries".
            package typealias Input = Google_Monitoring_V3_CreateTimeSeriesRequest
            /// Response type for "CreateTimeSeries".
            package typealias Output = SwiftProtobuf.Google_Protobuf_Empty
            /// Descriptor for "CreateTimeSeries".
            package static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.monitoring.v3.MetricService"),
                method: "CreateTimeSeries",
                type: .unary
            )
        }
        /// Namespace for "CreateServiceTimeSeries" metadata.
        package enum CreateServiceTimeSeries: Sendable {
            /// Request type for "CreateServiceTimeSeries".
            package typealias Input = Google_Monitoring_V3_CreateTimeSeriesRequest
            /// Response type for "CreateServiceTimeSeries".
            package typealias Output = SwiftProtobuf.Google_Protobuf_Empty
            /// Descriptor for "CreateServiceTimeSeries".
            package static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.monitoring.v3.MetricService"),
                method: "CreateServiceTimeSeries",
                type: .unary
            )
        }
        /// Descriptors for all methods in the "google.monitoring.v3.MetricService" service.
        package static let descriptors: [GRPCCore.MethodDescriptor] = [
            ListMonitoredResourceDescriptors.descriptor,
            GetMonitoredResourceDescriptor.descriptor,
            ListMetricDescriptors.descriptor,
            GetMetricDescriptor.descriptor,
            CreateMetricDescriptor.descriptor,
            DeleteMetricDescriptor.descriptor,
            ListTimeSeries.descriptor,
            CreateTimeSeries.descriptor,
            CreateServiceTimeSeries.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "google.monitoring.v3.MetricService" service.
    package static let google_monitoring_v3_MetricService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.monitoring.v3.MetricService")
}

// MARK: google.monitoring.v3.MetricService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Google_Monitoring_V3_MetricService {
    /// Generated client protocol for the "google.monitoring.v3.MetricService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Manages metric descriptors, monitored resource descriptors, and
    /// > time series data.
    package protocol ClientProtocol: Sendable {
        /// Call the "ListMonitoredResourceDescriptors" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Lists monitored resource descriptors that match a filter.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Monitoring_V3_ListMonitoredResourceDescriptorsRequest` message.
        ///   - serializer: A serializer for `Google_Monitoring_V3_ListMonitoredResourceDescriptorsRequest` messages.
        ///   - deserializer: A deserializer for `Google_Monitoring_V3_ListMonitoredResourceDescriptorsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        func listMonitoredResourceDescriptors<Result>(
            request: GRPCCore.ClientRequest<Google_Monitoring_V3_ListMonitoredResourceDescriptorsRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Monitoring_V3_ListMonitoredResourceDescriptorsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Monitoring_V3_ListMonitoredResourceDescriptorsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Monitoring_V3_ListMonitoredResourceDescriptorsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetMonitoredResourceDescriptor" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Gets a single monitored resource descriptor.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Monitoring_V3_GetMonitoredResourceDescriptorRequest` message.
        ///   - serializer: A serializer for `Google_Monitoring_V3_GetMonitoredResourceDescriptorRequest` messages.
        ///   - deserializer: A deserializer for `Google_Api_MonitoredResourceDescriptor` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        func getMonitoredResourceDescriptor<Result>(
            request: GRPCCore.ClientRequest<Google_Monitoring_V3_GetMonitoredResourceDescriptorRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Monitoring_V3_GetMonitoredResourceDescriptorRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Api_MonitoredResourceDescriptor>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Api_MonitoredResourceDescriptor>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ListMetricDescriptors" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Lists metric descriptors that match a filter.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Monitoring_V3_ListMetricDescriptorsRequest` message.
        ///   - serializer: A serializer for `Google_Monitoring_V3_ListMetricDescriptorsRequest` messages.
        ///   - deserializer: A deserializer for `Google_Monitoring_V3_ListMetricDescriptorsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        func listMetricDescriptors<Result>(
            request: GRPCCore.ClientRequest<Google_Monitoring_V3_ListMetricDescriptorsRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Monitoring_V3_ListMetricDescriptorsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Monitoring_V3_ListMetricDescriptorsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Monitoring_V3_ListMetricDescriptorsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetMetricDescriptor" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Gets a single metric descriptor.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Monitoring_V3_GetMetricDescriptorRequest` message.
        ///   - serializer: A serializer for `Google_Monitoring_V3_GetMetricDescriptorRequest` messages.
        ///   - deserializer: A deserializer for `Google_Api_MetricDescriptor` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        func getMetricDescriptor<Result>(
            request: GRPCCore.ClientRequest<Google_Monitoring_V3_GetMetricDescriptorRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Monitoring_V3_GetMetricDescriptorRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Api_MetricDescriptor>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Api_MetricDescriptor>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "CreateMetricDescriptor" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Creates a new metric descriptor.
        /// > The creation is executed asynchronously.
        /// > User-created metric descriptors define
        /// > [custom metrics](https://cloud.google.com/monitoring/custom-metrics).
        /// > The metric descriptor is updated if it already exists,
        /// > except that metric labels are never removed.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Monitoring_V3_CreateMetricDescriptorRequest` message.
        ///   - serializer: A serializer for `Google_Monitoring_V3_CreateMetricDescriptorRequest` messages.
        ///   - deserializer: A deserializer for `Google_Api_MetricDescriptor` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        func createMetricDescriptor<Result>(
            request: GRPCCore.ClientRequest<Google_Monitoring_V3_CreateMetricDescriptorRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Monitoring_V3_CreateMetricDescriptorRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Api_MetricDescriptor>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Api_MetricDescriptor>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "DeleteMetricDescriptor" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Deletes a metric descriptor. Only user-created
        /// > [custom metrics](https://cloud.google.com/monitoring/custom-metrics) can be
        /// > deleted.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Monitoring_V3_DeleteMetricDescriptorRequest` message.
        ///   - serializer: A serializer for `Google_Monitoring_V3_DeleteMetricDescriptorRequest` messages.
        ///   - deserializer: A deserializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        func deleteMetricDescriptor<Result>(
            request: GRPCCore.ClientRequest<Google_Monitoring_V3_DeleteMetricDescriptorRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Monitoring_V3_DeleteMetricDescriptorRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SwiftProtobuf.Google_Protobuf_Empty>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ListTimeSeries" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Lists time series that match a filter.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Monitoring_V3_ListTimeSeriesRequest` message.
        ///   - serializer: A serializer for `Google_Monitoring_V3_ListTimeSeriesRequest` messages.
        ///   - deserializer: A deserializer for `Google_Monitoring_V3_ListTimeSeriesResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        func listTimeSeries<Result>(
            request: GRPCCore.ClientRequest<Google_Monitoring_V3_ListTimeSeriesRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Monitoring_V3_ListTimeSeriesRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Monitoring_V3_ListTimeSeriesResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Monitoring_V3_ListTimeSeriesResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "CreateTimeSeries" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Creates or adds data to one or more time series.
        /// > The response is empty if all time series in the request were written.
        /// > If any time series could not be written, a corresponding failure message is
        /// > included in the error response.
        /// > This method does not support
        /// > [resource locations constraint of an organization
        /// > policy](https://cloud.google.com/resource-manager/docs/organization-policy/defining-locations#setting_the_organization_policy).
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Monitoring_V3_CreateTimeSeriesRequest` message.
        ///   - serializer: A serializer for `Google_Monitoring_V3_CreateTimeSeriesRequest` messages.
        ///   - deserializer: A deserializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        func createTimeSeries<Result>(
            request: GRPCCore.ClientRequest<Google_Monitoring_V3_CreateTimeSeriesRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Monitoring_V3_CreateTimeSeriesRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SwiftProtobuf.Google_Protobuf_Empty>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "CreateServiceTimeSeries" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Creates or adds data to one or more service time series. A service time
        /// > series is a time series for a metric from a Google Cloud service. The
        /// > response is empty if all time series in the request were written. If any
        /// > time series could not be written, a corresponding failure message is
        /// > included in the error response. This endpoint rejects writes to
        /// > user-defined metrics.
        /// > This method is only for use by Google Cloud services. Use
        /// > [projects.timeSeries.create][google.monitoring.v3.MetricService.CreateTimeSeries]
        /// > instead.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Monitoring_V3_CreateTimeSeriesRequest` message.
        ///   - serializer: A serializer for `Google_Monitoring_V3_CreateTimeSeriesRequest` messages.
        ///   - deserializer: A deserializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        func createServiceTimeSeries<Result>(
            request: GRPCCore.ClientRequest<Google_Monitoring_V3_CreateTimeSeriesRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Monitoring_V3_CreateTimeSeriesRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SwiftProtobuf.Google_Protobuf_Empty>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "google.monitoring.v3.MetricService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Manages metric descriptors, monitored resource descriptors, and
    /// > time series data.
    package struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        package init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "ListMonitoredResourceDescriptors" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Lists monitored resource descriptors that match a filter.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Monitoring_V3_ListMonitoredResourceDescriptorsRequest` message.
        ///   - serializer: A serializer for `Google_Monitoring_V3_ListMonitoredResourceDescriptorsRequest` messages.
        ///   - deserializer: A deserializer for `Google_Monitoring_V3_ListMonitoredResourceDescriptorsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        package func listMonitoredResourceDescriptors<Result>(
            request: GRPCCore.ClientRequest<Google_Monitoring_V3_ListMonitoredResourceDescriptorsRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Monitoring_V3_ListMonitoredResourceDescriptorsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Monitoring_V3_ListMonitoredResourceDescriptorsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Monitoring_V3_ListMonitoredResourceDescriptorsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Monitoring_V3_MetricService.Method.ListMonitoredResourceDescriptors.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "GetMonitoredResourceDescriptor" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Gets a single monitored resource descriptor.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Monitoring_V3_GetMonitoredResourceDescriptorRequest` message.
        ///   - serializer: A serializer for `Google_Monitoring_V3_GetMonitoredResourceDescriptorRequest` messages.
        ///   - deserializer: A deserializer for `Google_Api_MonitoredResourceDescriptor` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        package func getMonitoredResourceDescriptor<Result>(
            request: GRPCCore.ClientRequest<Google_Monitoring_V3_GetMonitoredResourceDescriptorRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Monitoring_V3_GetMonitoredResourceDescriptorRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Api_MonitoredResourceDescriptor>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Api_MonitoredResourceDescriptor>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Monitoring_V3_MetricService.Method.GetMonitoredResourceDescriptor.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ListMetricDescriptors" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Lists metric descriptors that match a filter.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Monitoring_V3_ListMetricDescriptorsRequest` message.
        ///   - serializer: A serializer for `Google_Monitoring_V3_ListMetricDescriptorsRequest` messages.
        ///   - deserializer: A deserializer for `Google_Monitoring_V3_ListMetricDescriptorsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        package func listMetricDescriptors<Result>(
            request: GRPCCore.ClientRequest<Google_Monitoring_V3_ListMetricDescriptorsRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Monitoring_V3_ListMetricDescriptorsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Monitoring_V3_ListMetricDescriptorsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Monitoring_V3_ListMetricDescriptorsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Monitoring_V3_MetricService.Method.ListMetricDescriptors.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "GetMetricDescriptor" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Gets a single metric descriptor.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Monitoring_V3_GetMetricDescriptorRequest` message.
        ///   - serializer: A serializer for `Google_Monitoring_V3_GetMetricDescriptorRequest` messages.
        ///   - deserializer: A deserializer for `Google_Api_MetricDescriptor` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        package func getMetricDescriptor<Result>(
            request: GRPCCore.ClientRequest<Google_Monitoring_V3_GetMetricDescriptorRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Monitoring_V3_GetMetricDescriptorRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Api_MetricDescriptor>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Api_MetricDescriptor>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Monitoring_V3_MetricService.Method.GetMetricDescriptor.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "CreateMetricDescriptor" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Creates a new metric descriptor.
        /// > The creation is executed asynchronously.
        /// > User-created metric descriptors define
        /// > [custom metrics](https://cloud.google.com/monitoring/custom-metrics).
        /// > The metric descriptor is updated if it already exists,
        /// > except that metric labels are never removed.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Monitoring_V3_CreateMetricDescriptorRequest` message.
        ///   - serializer: A serializer for `Google_Monitoring_V3_CreateMetricDescriptorRequest` messages.
        ///   - deserializer: A deserializer for `Google_Api_MetricDescriptor` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        package func createMetricDescriptor<Result>(
            request: GRPCCore.ClientRequest<Google_Monitoring_V3_CreateMetricDescriptorRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Monitoring_V3_CreateMetricDescriptorRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Api_MetricDescriptor>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Api_MetricDescriptor>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Monitoring_V3_MetricService.Method.CreateMetricDescriptor.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "DeleteMetricDescriptor" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Deletes a metric descriptor. Only user-created
        /// > [custom metrics](https://cloud.google.com/monitoring/custom-metrics) can be
        /// > deleted.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Monitoring_V3_DeleteMetricDescriptorRequest` message.
        ///   - serializer: A serializer for `Google_Monitoring_V3_DeleteMetricDescriptorRequest` messages.
        ///   - deserializer: A deserializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        package func deleteMetricDescriptor<Result>(
            request: GRPCCore.ClientRequest<Google_Monitoring_V3_DeleteMetricDescriptorRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Monitoring_V3_DeleteMetricDescriptorRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SwiftProtobuf.Google_Protobuf_Empty>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Monitoring_V3_MetricService.Method.DeleteMetricDescriptor.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ListTimeSeries" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Lists time series that match a filter.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Monitoring_V3_ListTimeSeriesRequest` message.
        ///   - serializer: A serializer for `Google_Monitoring_V3_ListTimeSeriesRequest` messages.
        ///   - deserializer: A deserializer for `Google_Monitoring_V3_ListTimeSeriesResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        package func listTimeSeries<Result>(
            request: GRPCCore.ClientRequest<Google_Monitoring_V3_ListTimeSeriesRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Monitoring_V3_ListTimeSeriesRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Monitoring_V3_ListTimeSeriesResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Monitoring_V3_ListTimeSeriesResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Monitoring_V3_MetricService.Method.ListTimeSeries.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "CreateTimeSeries" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Creates or adds data to one or more time series.
        /// > The response is empty if all time series in the request were written.
        /// > If any time series could not be written, a corresponding failure message is
        /// > included in the error response.
        /// > This method does not support
        /// > [resource locations constraint of an organization
        /// > policy](https://cloud.google.com/resource-manager/docs/organization-policy/defining-locations#setting_the_organization_policy).
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Monitoring_V3_CreateTimeSeriesRequest` message.
        ///   - serializer: A serializer for `Google_Monitoring_V3_CreateTimeSeriesRequest` messages.
        ///   - deserializer: A deserializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        package func createTimeSeries<Result>(
            request: GRPCCore.ClientRequest<Google_Monitoring_V3_CreateTimeSeriesRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Monitoring_V3_CreateTimeSeriesRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SwiftProtobuf.Google_Protobuf_Empty>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Monitoring_V3_MetricService.Method.CreateTimeSeries.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "CreateServiceTimeSeries" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Creates or adds data to one or more service time series. A service time
        /// > series is a time series for a metric from a Google Cloud service. The
        /// > response is empty if all time series in the request were written. If any
        /// > time series could not be written, a corresponding failure message is
        /// > included in the error response. This endpoint rejects writes to
        /// > user-defined metrics.
        /// > This method is only for use by Google Cloud services. Use
        /// > [projects.timeSeries.create][google.monitoring.v3.MetricService.CreateTimeSeries]
        /// > instead.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Monitoring_V3_CreateTimeSeriesRequest` message.
        ///   - serializer: A serializer for `Google_Monitoring_V3_CreateTimeSeriesRequest` messages.
        ///   - deserializer: A deserializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        package func createServiceTimeSeries<Result>(
            request: GRPCCore.ClientRequest<Google_Monitoring_V3_CreateTimeSeriesRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Monitoring_V3_CreateTimeSeriesRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SwiftProtobuf.Google_Protobuf_Empty>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Monitoring_V3_MetricService.Method.CreateServiceTimeSeries.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Google_Monitoring_V3_MetricService.ClientProtocol {
    /// Call the "ListMonitoredResourceDescriptors" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Lists monitored resource descriptors that match a filter.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Monitoring_V3_ListMonitoredResourceDescriptorsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    package func listMonitoredResourceDescriptors<Result>(
        request: GRPCCore.ClientRequest<Google_Monitoring_V3_ListMonitoredResourceDescriptorsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Monitoring_V3_ListMonitoredResourceDescriptorsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.listMonitoredResourceDescriptors(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Monitoring_V3_ListMonitoredResourceDescriptorsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Google_Monitoring_V3_ListMonitoredResourceDescriptorsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetMonitoredResourceDescriptor" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Gets a single monitored resource descriptor.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Monitoring_V3_GetMonitoredResourceDescriptorRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    package func getMonitoredResourceDescriptor<Result>(
        request: GRPCCore.ClientRequest<Google_Monitoring_V3_GetMonitoredResourceDescriptorRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Api_MonitoredResourceDescriptor>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getMonitoredResourceDescriptor(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Monitoring_V3_GetMonitoredResourceDescriptorRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Google_Api_MonitoredResourceDescriptor>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListMetricDescriptors" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Lists metric descriptors that match a filter.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Monitoring_V3_ListMetricDescriptorsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    package func listMetricDescriptors<Result>(
        request: GRPCCore.ClientRequest<Google_Monitoring_V3_ListMetricDescriptorsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Monitoring_V3_ListMetricDescriptorsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.listMetricDescriptors(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Monitoring_V3_ListMetricDescriptorsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Google_Monitoring_V3_ListMetricDescriptorsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetMetricDescriptor" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Gets a single metric descriptor.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Monitoring_V3_GetMetricDescriptorRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    package func getMetricDescriptor<Result>(
        request: GRPCCore.ClientRequest<Google_Monitoring_V3_GetMetricDescriptorRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Api_MetricDescriptor>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getMetricDescriptor(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Monitoring_V3_GetMetricDescriptorRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Google_Api_MetricDescriptor>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CreateMetricDescriptor" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Creates a new metric descriptor.
    /// > The creation is executed asynchronously.
    /// > User-created metric descriptors define
    /// > [custom metrics](https://cloud.google.com/monitoring/custom-metrics).
    /// > The metric descriptor is updated if it already exists,
    /// > except that metric labels are never removed.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Monitoring_V3_CreateMetricDescriptorRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    package func createMetricDescriptor<Result>(
        request: GRPCCore.ClientRequest<Google_Monitoring_V3_CreateMetricDescriptorRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Api_MetricDescriptor>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.createMetricDescriptor(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Monitoring_V3_CreateMetricDescriptorRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Google_Api_MetricDescriptor>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DeleteMetricDescriptor" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Deletes a metric descriptor. Only user-created
    /// > [custom metrics](https://cloud.google.com/monitoring/custom-metrics) can be
    /// > deleted.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Monitoring_V3_DeleteMetricDescriptorRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    package func deleteMetricDescriptor<Result>(
        request: GRPCCore.ClientRequest<Google_Monitoring_V3_DeleteMetricDescriptorRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.deleteMetricDescriptor(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Monitoring_V3_DeleteMetricDescriptorRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<SwiftProtobuf.Google_Protobuf_Empty>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListTimeSeries" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Lists time series that match a filter.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Monitoring_V3_ListTimeSeriesRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    package func listTimeSeries<Result>(
        request: GRPCCore.ClientRequest<Google_Monitoring_V3_ListTimeSeriesRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Monitoring_V3_ListTimeSeriesResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.listTimeSeries(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Monitoring_V3_ListTimeSeriesRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Google_Monitoring_V3_ListTimeSeriesResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CreateTimeSeries" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Creates or adds data to one or more time series.
    /// > The response is empty if all time series in the request were written.
    /// > If any time series could not be written, a corresponding failure message is
    /// > included in the error response.
    /// > This method does not support
    /// > [resource locations constraint of an organization
    /// > policy](https://cloud.google.com/resource-manager/docs/organization-policy/defining-locations#setting_the_organization_policy).
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Monitoring_V3_CreateTimeSeriesRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    package func createTimeSeries<Result>(
        request: GRPCCore.ClientRequest<Google_Monitoring_V3_CreateTimeSeriesRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.createTimeSeries(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Monitoring_V3_CreateTimeSeriesRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<SwiftProtobuf.Google_Protobuf_Empty>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CreateServiceTimeSeries" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Creates or adds data to one or more service time series. A service time
    /// > series is a time series for a metric from a Google Cloud service. The
    /// > response is empty if all time series in the request were written. If any
    /// > time series could not be written, a corresponding failure message is
    /// > included in the error response. This endpoint rejects writes to
    /// > user-defined metrics.
    /// > This method is only for use by Google Cloud services. Use
    /// > [projects.timeSeries.create][google.monitoring.v3.MetricService.CreateTimeSeries]
    /// > instead.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Monitoring_V3_CreateTimeSeriesRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    package func createServiceTimeSeries<Result>(
        request: GRPCCore.ClientRequest<Google_Monitoring_V3_CreateTimeSeriesRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.createServiceTimeSeries(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Monitoring_V3_CreateTimeSeriesRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<SwiftProtobuf.Google_Protobuf_Empty>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Google_Monitoring_V3_MetricService.ClientProtocol {
    /// Call the "ListMonitoredResourceDescriptors" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Lists monitored resource descriptors that match a filter.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    package func listMonitoredResourceDescriptors<Result>(
        _ message: Google_Monitoring_V3_ListMonitoredResourceDescriptorsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Monitoring_V3_ListMonitoredResourceDescriptorsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Monitoring_V3_ListMonitoredResourceDescriptorsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.listMonitoredResourceDescriptors(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetMonitoredResourceDescriptor" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Gets a single monitored resource descriptor.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    package func getMonitoredResourceDescriptor<Result>(
        _ message: Google_Monitoring_V3_GetMonitoredResourceDescriptorRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Api_MonitoredResourceDescriptor>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Monitoring_V3_GetMonitoredResourceDescriptorRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getMonitoredResourceDescriptor(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListMetricDescriptors" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Lists metric descriptors that match a filter.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    package func listMetricDescriptors<Result>(
        _ message: Google_Monitoring_V3_ListMetricDescriptorsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Monitoring_V3_ListMetricDescriptorsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Monitoring_V3_ListMetricDescriptorsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.listMetricDescriptors(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetMetricDescriptor" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Gets a single metric descriptor.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    package func getMetricDescriptor<Result>(
        _ message: Google_Monitoring_V3_GetMetricDescriptorRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Api_MetricDescriptor>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Monitoring_V3_GetMetricDescriptorRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getMetricDescriptor(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CreateMetricDescriptor" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Creates a new metric descriptor.
    /// > The creation is executed asynchronously.
    /// > User-created metric descriptors define
    /// > [custom metrics](https://cloud.google.com/monitoring/custom-metrics).
    /// > The metric descriptor is updated if it already exists,
    /// > except that metric labels are never removed.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    package func createMetricDescriptor<Result>(
        _ message: Google_Monitoring_V3_CreateMetricDescriptorRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Api_MetricDescriptor>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Monitoring_V3_CreateMetricDescriptorRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.createMetricDescriptor(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DeleteMetricDescriptor" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Deletes a metric descriptor. Only user-created
    /// > [custom metrics](https://cloud.google.com/monitoring/custom-metrics) can be
    /// > deleted.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    package func deleteMetricDescriptor<Result>(
        _ message: Google_Monitoring_V3_DeleteMetricDescriptorRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Monitoring_V3_DeleteMetricDescriptorRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.deleteMetricDescriptor(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListTimeSeries" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Lists time series that match a filter.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    package func listTimeSeries<Result>(
        _ message: Google_Monitoring_V3_ListTimeSeriesRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Monitoring_V3_ListTimeSeriesResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Monitoring_V3_ListTimeSeriesRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.listTimeSeries(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CreateTimeSeries" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Creates or adds data to one or more time series.
    /// > The response is empty if all time series in the request were written.
    /// > If any time series could not be written, a corresponding failure message is
    /// > included in the error response.
    /// > This method does not support
    /// > [resource locations constraint of an organization
    /// > policy](https://cloud.google.com/resource-manager/docs/organization-policy/defining-locations#setting_the_organization_policy).
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    package func createTimeSeries<Result>(
        _ message: Google_Monitoring_V3_CreateTimeSeriesRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Monitoring_V3_CreateTimeSeriesRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.createTimeSeries(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CreateServiceTimeSeries" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Creates or adds data to one or more service time series. A service time
    /// > series is a time series for a metric from a Google Cloud service. The
    /// > response is empty if all time series in the request were written. If any
    /// > time series could not be written, a corresponding failure message is
    /// > included in the error response. This endpoint rejects writes to
    /// > user-defined metrics.
    /// > This method is only for use by Google Cloud services. Use
    /// > [projects.timeSeries.create][google.monitoring.v3.MetricService.CreateTimeSeries]
    /// > instead.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    package func createServiceTimeSeries<Result>(
        _ message: Google_Monitoring_V3_CreateTimeSeriesRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Monitoring_V3_CreateTimeSeriesRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.createServiceTimeSeries(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}