// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: google/monitoring/v3/metric_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// The `ListMonitoredResourceDescriptors` request.
package nonisolated struct Google_Monitoring_V3_ListMonitoredResourceDescriptorsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Required. The
  /// [project](https://cloud.google.com/monitoring/api/v3#project_name) on which
  /// to execute the request. The format is:
  ///
  ///     projects/[PROJECT_ID_OR_NUMBER]
  package var name: String = String()

  /// An optional [filter](https://cloud.google.com/monitoring/api/v3/filters)
  /// describing the descriptors to be returned.  The filter can reference the
  /// descriptor's type and labels. For example, the following filter returns
  /// only Google Compute Engine descriptors that have an `id` label:
  ///
  ///     resource.type = starts_with("gce_") AND resource.label:id
  package var filter: String = String()

  /// A positive number that is the maximum number of results to return.
  package var pageSize: Int32 = 0

  /// If this field is not empty then it must contain the `nextPageToken` value
  /// returned by a previous call to this method.  Using this field causes the
  /// method to return additional results from the previous method call.
  package var pageToken: String = String()

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}
}

/// The `ListMonitoredResourceDescriptors` response.
package nonisolated struct Google_Monitoring_V3_ListMonitoredResourceDescriptorsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The monitored resource descriptors that are available to this project
  /// and that match `filter`, if present.
  package var resourceDescriptors: [Google_Api_MonitoredResourceDescriptor] = []

  /// If there are more results than have been returned, then this field is set
  /// to a non-empty value.  To see the additional results,
  /// use that value as `page_token` in the next call to this method.
  package var nextPageToken: String = String()

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}
}

/// The `GetMonitoredResourceDescriptor` request.
package nonisolated struct Google_Monitoring_V3_GetMonitoredResourceDescriptorRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Required. The monitored resource descriptor to get.  The format is:
  ///
  ///     projects/[PROJECT_ID_OR_NUMBER]/monitoredResourceDescriptors/[RESOURCE_TYPE]
  ///
  /// The `[RESOURCE_TYPE]` is a predefined type, such as
  /// `cloudsql_database`.
  package var name: String = String()

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}
}

/// The `ListMetricDescriptors` request.
package nonisolated struct Google_Monitoring_V3_ListMetricDescriptorsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Required. The
  /// [project](https://cloud.google.com/monitoring/api/v3#project_name) on which
  /// to execute the request. The format is:
  ///
  ///     projects/[PROJECT_ID_OR_NUMBER]
  package var name: String = String()

  /// If this field is empty, all custom and
  /// system-defined metric descriptors are returned.
  /// Otherwise, the [filter](https://cloud.google.com/monitoring/api/v3/filters)
  /// specifies which metric descriptors are to be
  /// returned. For example, the following filter matches all
  /// [custom metrics](https://cloud.google.com/monitoring/custom-metrics):
  ///
  ///     metric.type = starts_with("custom.googleapis.com/")
  package var filter: String = String()

  /// A positive number that is the maximum number of results to return. The
  /// default and maximum value is 10,000. If a page_size <= 0 or > 10,000 is
  /// submitted, will instead return a maximum of 10,000 results.
  package var pageSize: Int32 = 0

  /// If this field is not empty then it must contain the `nextPageToken` value
  /// returned by a previous call to this method.  Using this field causes the
  /// method to return additional results from the previous method call.
  package var pageToken: String = String()

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}
}

/// The `ListMetricDescriptors` response.
package nonisolated struct Google_Monitoring_V3_ListMetricDescriptorsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The metric descriptors that are available to the project
  /// and that match the value of `filter`, if present.
  package var metricDescriptors: [Google_Api_MetricDescriptor] = []

  /// If there are more results than have been returned, then this field is set
  /// to a non-empty value.  To see the additional results,
  /// use that value as `page_token` in the next call to this method.
  package var nextPageToken: String = String()

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}
}

/// The `GetMetricDescriptor` request.
package nonisolated struct Google_Monitoring_V3_GetMetricDescriptorRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Required. The metric descriptor on which to execute the request. The format
  /// is:
  ///
  ///     projects/[PROJECT_ID_OR_NUMBER]/metricDescriptors/[METRIC_ID]
  ///
  /// An example value of `[METRIC_ID]` is
  /// `"compute.googleapis.com/instance/disk/read_bytes_count"`.
  package var name: String = String()

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}
}

/// The `CreateMetricDescriptor` request.
package nonisolated struct Google_Monitoring_V3_CreateMetricDescriptorRequest: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Required. The
  /// [project](https://cloud.google.com/monitoring/api/v3#project_name) on which
  /// to execute the request. The format is:
  /// 4
  ///     projects/[PROJECT_ID_OR_NUMBER]
  package var name: String {
    get {_storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  /// Required. The new [custom
  /// metric](https://cloud.google.com/monitoring/custom-metrics) descriptor.
  package var metricDescriptor: Google_Api_MetricDescriptor {
    get {_storage._metricDescriptor ?? Google_Api_MetricDescriptor()}
    set {_uniqueStorage()._metricDescriptor = newValue}
  }
  /// Returns true if `metricDescriptor` has been explicitly set.
  package var hasMetricDescriptor: Bool {_storage._metricDescriptor != nil}
  /// Clears the value of `metricDescriptor`. Subsequent reads from it will return its default value.
  package mutating func clearMetricDescriptor() {_uniqueStorage()._metricDescriptor = nil}

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// The `DeleteMetricDescriptor` request.
package nonisolated struct Google_Monitoring_V3_DeleteMetricDescriptorRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Required. The metric descriptor on which to execute the request. The format
  /// is:
  ///
  ///     projects/[PROJECT_ID_OR_NUMBER]/metricDescriptors/[METRIC_ID]
  ///
  /// An example of `[METRIC_ID]` is:
  /// `"custom.googleapis.com/my_test_metric"`.
  package var name: String = String()

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}
}

/// The `ListTimeSeries` request.
package nonisolated struct Google_Monitoring_V3_ListTimeSeriesRequest: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Required. The
  /// [project](https://cloud.google.com/monitoring/api/v3#project_name),
  /// organization or folder on which to execute the request. The format is:
  ///
  ///     projects/[PROJECT_ID_OR_NUMBER]
  ///     organizations/[ORGANIZATION_ID]
  ///     folders/[FOLDER_ID]
  package var name: String {
    get {_storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  /// Required. A [monitoring
  /// filter](https://cloud.google.com/monitoring/api/v3/filters) that specifies
  /// which time series should be returned.  The filter must specify a single
  /// metric type, and can additionally specify metric labels and other
  /// information. For example:
  ///
  ///     metric.type = "compute.googleapis.com/instance/cpu/usage_time" AND
  ///         metric.labels.instance_name = "my-instance-name"
  package var filter: String {
    get {_storage._filter}
    set {_uniqueStorage()._filter = newValue}
  }

  /// Required. The time interval for which results should be returned. Only time
  /// series that contain data points in the specified interval are included in
  /// the response.
  package var interval: Google_Monitoring_V3_TimeInterval {
    get {_storage._interval ?? Google_Monitoring_V3_TimeInterval()}
    set {_uniqueStorage()._interval = newValue}
  }
  /// Returns true if `interval` has been explicitly set.
  package var hasInterval: Bool {_storage._interval != nil}
  /// Clears the value of `interval`. Subsequent reads from it will return its default value.
  package mutating func clearInterval() {_uniqueStorage()._interval = nil}

  /// Specifies the alignment of data points in individual time series as
  /// well as how to combine the retrieved time series across specified labels.
  ///
  /// By default (if no `aggregation` is explicitly specified), the raw time
  /// series data is returned.
  package var aggregation: Google_Monitoring_V3_Aggregation {
    get {_storage._aggregation ?? Google_Monitoring_V3_Aggregation()}
    set {_uniqueStorage()._aggregation = newValue}
  }
  /// Returns true if `aggregation` has been explicitly set.
  package var hasAggregation: Bool {_storage._aggregation != nil}
  /// Clears the value of `aggregation`. Subsequent reads from it will return its default value.
  package mutating func clearAggregation() {_uniqueStorage()._aggregation = nil}

  /// Apply a second aggregation after `aggregation` is applied. May only be
  /// specified if `aggregation` is specified.
  package var secondaryAggregation: Google_Monitoring_V3_Aggregation {
    get {_storage._secondaryAggregation ?? Google_Monitoring_V3_Aggregation()}
    set {_uniqueStorage()._secondaryAggregation = newValue}
  }
  /// Returns true if `secondaryAggregation` has been explicitly set.
  package var hasSecondaryAggregation: Bool {_storage._secondaryAggregation != nil}
  /// Clears the value of `secondaryAggregation`. Subsequent reads from it will return its default value.
  package mutating func clearSecondaryAggregation() {_uniqueStorage()._secondaryAggregation = nil}

  /// Unsupported: must be left blank. The points in each time series are
  /// currently returned in reverse time order (most recent to oldest).
  package var orderBy: String {
    get {_storage._orderBy}
    set {_uniqueStorage()._orderBy = newValue}
  }

  /// Required. Specifies which information is returned about the time series.
  package var view: Google_Monitoring_V3_ListTimeSeriesRequest.TimeSeriesView {
    get {_storage._view}
    set {_uniqueStorage()._view = newValue}
  }

  /// A positive number that is the maximum number of results to return. If
  /// `page_size` is empty or more than 100,000 results, the effective
  /// `page_size` is 100,000 results. If `view` is set to `FULL`, this is the
  /// maximum number of `Points` returned. If `view` is set to `HEADERS`, this is
  /// the maximum number of `TimeSeries` returned.
  package var pageSize: Int32 {
    get {_storage._pageSize}
    set {_uniqueStorage()._pageSize = newValue}
  }

  /// If this field is not empty then it must contain the `nextPageToken` value
  /// returned by a previous call to this method.  Using this field causes the
  /// method to return additional results from the previous method call.
  package var pageToken: String {
    get {_storage._pageToken}
    set {_uniqueStorage()._pageToken = newValue}
  }

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Controls which fields are returned by `ListTimeSeries*`.
  package nonisolated enum TimeSeriesView: SwiftProtobuf.Enum, Swift.CaseIterable {
    package typealias RawValue = Int

    /// Returns the identity of the metric(s), the time series,
    /// and the time series data.
    case full // = 0

    /// Returns the identity of the metric and the time series resource,
    /// but not the time series data.
    case headers // = 1
    case UNRECOGNIZED(Int)

    package init() {
      self = .full
    }

    package init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .full
      case 1: self = .headers
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    package var rawValue: Int {
      switch self {
      case .full: return 0
      case .headers: return 1
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    package static let allCases: [Google_Monitoring_V3_ListTimeSeriesRequest.TimeSeriesView] = [
      .full,
      .headers,
    ]

  }

  package init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// The `ListTimeSeries` response.
package nonisolated struct Google_Monitoring_V3_ListTimeSeriesResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// One or more time series that match the filter included in the request.
  package var timeSeries: [Google_Monitoring_V3_TimeSeries] = []

  /// If there are more results than have been returned, then this field is set
  /// to a non-empty value.  To see the additional results,
  /// use that value as `page_token` in the next call to this method.
  package var nextPageToken: String = String()

  /// Query execution errors that may have caused the time series data returned
  /// to be incomplete.
  package var executionErrors: [Google_Rpc_Status] = []

  /// The unit in which all `time_series` point values are reported. `unit`
  /// follows the UCUM format for units as seen in
  /// https://unitsofmeasure.org/ucum.html.
  /// If different `time_series` have different units (for example, because they
  /// come from different metric types, or a unit is absent), then `unit` will be
  /// "{not_a_unit}".
  package var unit: String = String()

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}
}

/// The `CreateTimeSeries` request.
package nonisolated struct Google_Monitoring_V3_CreateTimeSeriesRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Required. The
  /// [project](https://cloud.google.com/monitoring/api/v3#project_name) on which
  /// to execute the request. The format is:
  ///
  ///     projects/[PROJECT_ID_OR_NUMBER]
  package var name: String = String()

  /// Required. The new data to be added to a list of time series.
  /// Adds at most one data point to each of several time series.  The new data
  /// point must be more recent than any other point in its time series.  Each
  /// `TimeSeries` value must fully specify a unique time series by supplying
  /// all label values for the metric and the monitored resource.
  ///
  /// The maximum number of `TimeSeries` objects per `Create` request is 200.
  package var timeSeries: [Google_Monitoring_V3_TimeSeries] = []

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}
}

/// DEPRECATED. Used to hold per-time-series error status.
package nonisolated struct Google_Monitoring_V3_CreateTimeSeriesError: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// DEPRECATED. Time series ID that resulted in the `status` error.
  ///
  /// NOTE: This field was marked as deprecated in the .proto file.
  package var timeSeries: Google_Monitoring_V3_TimeSeries {
    get {_timeSeries ?? Google_Monitoring_V3_TimeSeries()}
    set {_timeSeries = newValue}
  }
  /// Returns true if `timeSeries` has been explicitly set.
  package var hasTimeSeries: Bool {self._timeSeries != nil}
  /// Clears the value of `timeSeries`. Subsequent reads from it will return its default value.
  package mutating func clearTimeSeries() {self._timeSeries = nil}

  /// DEPRECATED. The status of the requested write operation for `time_series`.
  ///
  /// NOTE: This field was marked as deprecated in the .proto file.
  package var status: Google_Rpc_Status {
    get {_status ?? Google_Rpc_Status()}
    set {_status = newValue}
  }
  /// Returns true if `status` has been explicitly set.
  package var hasStatus: Bool {self._status != nil}
  /// Clears the value of `status`. Subsequent reads from it will return its default value.
  package mutating func clearStatus() {self._status = nil}

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}

  fileprivate var _timeSeries: Google_Monitoring_V3_TimeSeries? = nil
  fileprivate var _status: Google_Rpc_Status? = nil
}

/// Summary of the result of a failed request to write data to a time series.
package nonisolated struct Google_Monitoring_V3_CreateTimeSeriesSummary: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The number of points in the request.
  package var totalPointCount: Int32 = 0

  /// The number of points that were successfully written.
  package var successPointCount: Int32 = 0

  /// The number of points that failed to be written. Order is not guaranteed.
  package var errors: [Google_Monitoring_V3_CreateTimeSeriesSummary.Error] = []

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Detailed information about an error category.
  package nonisolated struct Error: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The status of the requested write operation.
    package var status: Google_Rpc_Status {
      get {_status ?? Google_Rpc_Status()}
      set {_status = newValue}
    }
    /// Returns true if `status` has been explicitly set.
    package var hasStatus: Bool {self._status != nil}
    /// Clears the value of `status`. Subsequent reads from it will return its default value.
    package mutating func clearStatus() {self._status = nil}

    /// The number of points that couldn't be written because of `status`.
    package var pointCount: Int32 = 0

    package var unknownFields = SwiftProtobuf.UnknownStorage()

    package init() {}

    fileprivate var _status: Google_Rpc_Status? = nil
  }

  package init() {}
}

/// The `QueryTimeSeries` request.
package nonisolated struct Google_Monitoring_V3_QueryTimeSeriesRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Required. The
  /// [project](https://cloud.google.com/monitoring/api/v3#project_name) on which
  /// to execute the request. The format is:
  ///
  ///     projects/[PROJECT_ID_OR_NUMBER]
  package var name: String = String()

  /// Required. The query in the [Monitoring Query
  /// Language](https://cloud.google.com/monitoring/mql/reference) format.
  /// The default time zone is in UTC.
  package var query: String = String()

  /// A positive number that is the maximum number of time_series_data to return.
  package var pageSize: Int32 = 0

  /// If this field is not empty then it must contain the `nextPageToken` value
  /// returned by a previous call to this method.  Using this field causes the
  /// method to return additional results from the previous method call.
  package var pageToken: String = String()

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}
}

/// The `QueryTimeSeries` response.
package nonisolated struct Google_Monitoring_V3_QueryTimeSeriesResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The descriptor for the time series data.
  package var timeSeriesDescriptor: Google_Monitoring_V3_TimeSeriesDescriptor {
    get {_timeSeriesDescriptor ?? Google_Monitoring_V3_TimeSeriesDescriptor()}
    set {_timeSeriesDescriptor = newValue}
  }
  /// Returns true if `timeSeriesDescriptor` has been explicitly set.
  package var hasTimeSeriesDescriptor: Bool {self._timeSeriesDescriptor != nil}
  /// Clears the value of `timeSeriesDescriptor`. Subsequent reads from it will return its default value.
  package mutating func clearTimeSeriesDescriptor() {self._timeSeriesDescriptor = nil}

  /// The time series data.
  package var timeSeriesData: [Google_Monitoring_V3_TimeSeriesData] = []

  /// If there are more results than have been returned, then this field is set
  /// to a non-empty value.  To see the additional results, use that value as
  /// `page_token` in the next call to this method.
  package var nextPageToken: String = String()

  /// Query execution errors that may have caused the time series data returned
  /// to be incomplete. The available data will be available in the
  /// response.
  package var partialErrors: [Google_Rpc_Status] = []

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}

  fileprivate var _timeSeriesDescriptor: Google_Monitoring_V3_TimeSeriesDescriptor? = nil
}

/// This is an error detail intended to be used with INVALID_ARGUMENT errors.
package nonisolated struct Google_Monitoring_V3_QueryErrorList: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Errors in parsing the time series query language text. The number of errors
  /// in the response may be limited.
  package var errors: [Google_Monitoring_V3_QueryError] = []

  /// A summary of all the errors.
  package var errorSummary: String = String()

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "google.monitoring.v3"

nonisolated extension Google_Monitoring_V3_ListMonitoredResourceDescriptorsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".ListMonitoredResourceDescriptorsRequest"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}filter\0\u{3}page_size\0\u{3}page_token\0\u{1}name\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeSingularStringField(value: &self.filter) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.pageSize) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.pageToken) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.name) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.filter.isEmpty {
      try visitor.visitSingularStringField(value: self.filter, fieldNumber: 2)
    }
    if self.pageSize != 0 {
      try visitor.visitSingularInt32Field(value: self.pageSize, fieldNumber: 3)
    }
    if !self.pageToken.isEmpty {
      try visitor.visitSingularStringField(value: self.pageToken, fieldNumber: 4)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Monitoring_V3_ListMonitoredResourceDescriptorsRequest, rhs: Google_Monitoring_V3_ListMonitoredResourceDescriptorsRequest) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.filter != rhs.filter {return false}
    if lhs.pageSize != rhs.pageSize {return false}
    if lhs.pageToken != rhs.pageToken {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Monitoring_V3_ListMonitoredResourceDescriptorsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".ListMonitoredResourceDescriptorsResponse"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}resource_descriptors\0\u{3}next_page_token\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.resourceDescriptors) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.nextPageToken) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.resourceDescriptors.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.resourceDescriptors, fieldNumber: 1)
    }
    if !self.nextPageToken.isEmpty {
      try visitor.visitSingularStringField(value: self.nextPageToken, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Monitoring_V3_ListMonitoredResourceDescriptorsResponse, rhs: Google_Monitoring_V3_ListMonitoredResourceDescriptorsResponse) -> Bool {
    if lhs.resourceDescriptors != rhs.resourceDescriptors {return false}
    if lhs.nextPageToken != rhs.nextPageToken {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Monitoring_V3_GetMonitoredResourceDescriptorRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".GetMonitoredResourceDescriptorRequest"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{3}name\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 3: try { try decoder.decodeSingularStringField(value: &self.name) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Monitoring_V3_GetMonitoredResourceDescriptorRequest, rhs: Google_Monitoring_V3_GetMonitoredResourceDescriptorRequest) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Monitoring_V3_ListMetricDescriptorsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".ListMetricDescriptorsRequest"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}filter\0\u{3}page_size\0\u{3}page_token\0\u{1}name\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeSingularStringField(value: &self.filter) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.pageSize) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.pageToken) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.name) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.filter.isEmpty {
      try visitor.visitSingularStringField(value: self.filter, fieldNumber: 2)
    }
    if self.pageSize != 0 {
      try visitor.visitSingularInt32Field(value: self.pageSize, fieldNumber: 3)
    }
    if !self.pageToken.isEmpty {
      try visitor.visitSingularStringField(value: self.pageToken, fieldNumber: 4)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Monitoring_V3_ListMetricDescriptorsRequest, rhs: Google_Monitoring_V3_ListMetricDescriptorsRequest) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.filter != rhs.filter {return false}
    if lhs.pageSize != rhs.pageSize {return false}
    if lhs.pageToken != rhs.pageToken {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Monitoring_V3_ListMetricDescriptorsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".ListMetricDescriptorsResponse"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}metric_descriptors\0\u{3}next_page_token\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.metricDescriptors) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.nextPageToken) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.metricDescriptors.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.metricDescriptors, fieldNumber: 1)
    }
    if !self.nextPageToken.isEmpty {
      try visitor.visitSingularStringField(value: self.nextPageToken, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Monitoring_V3_ListMetricDescriptorsResponse, rhs: Google_Monitoring_V3_ListMetricDescriptorsResponse) -> Bool {
    if lhs.metricDescriptors != rhs.metricDescriptors {return false}
    if lhs.nextPageToken != rhs.nextPageToken {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Monitoring_V3_GetMetricDescriptorRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".GetMetricDescriptorRequest"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{3}name\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 3: try { try decoder.decodeSingularStringField(value: &self.name) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Monitoring_V3_GetMetricDescriptorRequest, rhs: Google_Monitoring_V3_GetMetricDescriptorRequest) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Monitoring_V3_CreateMetricDescriptorRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".CreateMetricDescriptorRequest"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{2}metric_descriptor\0\u{1}name\0")

  fileprivate class _StorageClass {
    var _name: String = String()
    var _metricDescriptor: Google_Api_MetricDescriptor? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _name = source._name
      _metricDescriptor = source._metricDescriptor
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._metricDescriptor) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        default: break
        }
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._metricDescriptor {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 3)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Monitoring_V3_CreateMetricDescriptorRequest, rhs: Google_Monitoring_V3_CreateMetricDescriptorRequest) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._name != rhs_storage._name {return false}
        if _storage._metricDescriptor != rhs_storage._metricDescriptor {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Monitoring_V3_DeleteMetricDescriptorRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".DeleteMetricDescriptorRequest"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{3}name\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 3: try { try decoder.decodeSingularStringField(value: &self.name) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Monitoring_V3_DeleteMetricDescriptorRequest, rhs: Google_Monitoring_V3_DeleteMetricDescriptorRequest) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Monitoring_V3_ListTimeSeriesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".ListTimeSeriesRequest"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}filter\0\u{2}\u{2}interval\0\u{1}aggregation\0\u{3}order_by\0\u{1}view\0\u{3}page_size\0\u{3}page_token\0\u{1}name\0\u{3}secondary_aggregation\0")

  fileprivate class _StorageClass {
    var _name: String = String()
    var _filter: String = String()
    var _interval: Google_Monitoring_V3_TimeInterval? = nil
    var _aggregation: Google_Monitoring_V3_Aggregation? = nil
    var _secondaryAggregation: Google_Monitoring_V3_Aggregation? = nil
    var _orderBy: String = String()
    var _view: Google_Monitoring_V3_ListTimeSeriesRequest.TimeSeriesView = .full
    var _pageSize: Int32 = 0
    var _pageToken: String = String()

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _name = source._name
      _filter = source._filter
      _interval = source._interval
      _aggregation = source._aggregation
      _secondaryAggregation = source._secondaryAggregation
      _orderBy = source._orderBy
      _view = source._view
      _pageSize = source._pageSize
      _pageToken = source._pageToken
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._filter) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._interval) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._aggregation) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._orderBy) }()
        case 7: try { try decoder.decodeSingularEnumField(value: &_storage._view) }()
        case 8: try { try decoder.decodeSingularInt32Field(value: &_storage._pageSize) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._pageToken) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 11: try { try decoder.decodeSingularMessageField(value: &_storage._secondaryAggregation) }()
        default: break
        }
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._filter.isEmpty {
        try visitor.visitSingularStringField(value: _storage._filter, fieldNumber: 2)
      }
      try { if let v = _storage._interval {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._aggregation {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      if !_storage._orderBy.isEmpty {
        try visitor.visitSingularStringField(value: _storage._orderBy, fieldNumber: 6)
      }
      if _storage._view != .full {
        try visitor.visitSingularEnumField(value: _storage._view, fieldNumber: 7)
      }
      if _storage._pageSize != 0 {
        try visitor.visitSingularInt32Field(value: _storage._pageSize, fieldNumber: 8)
      }
      if !_storage._pageToken.isEmpty {
        try visitor.visitSingularStringField(value: _storage._pageToken, fieldNumber: 9)
      }
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 10)
      }
      try { if let v = _storage._secondaryAggregation {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Monitoring_V3_ListTimeSeriesRequest, rhs: Google_Monitoring_V3_ListTimeSeriesRequest) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._name != rhs_storage._name {return false}
        if _storage._filter != rhs_storage._filter {return false}
        if _storage._interval != rhs_storage._interval {return false}
        if _storage._aggregation != rhs_storage._aggregation {return false}
        if _storage._secondaryAggregation != rhs_storage._secondaryAggregation {return false}
        if _storage._orderBy != rhs_storage._orderBy {return false}
        if _storage._view != rhs_storage._view {return false}
        if _storage._pageSize != rhs_storage._pageSize {return false}
        if _storage._pageToken != rhs_storage._pageToken {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Monitoring_V3_ListTimeSeriesRequest.TimeSeriesView: SwiftProtobuf._ProtoNameProviding {
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0FULL\0\u{1}HEADERS\0")
}

nonisolated extension Google_Monitoring_V3_ListTimeSeriesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".ListTimeSeriesResponse"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}time_series\0\u{3}next_page_token\0\u{3}execution_errors\0\u{2}\u{2}unit\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.timeSeries) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.nextPageToken) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.executionErrors) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.unit) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.timeSeries.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.timeSeries, fieldNumber: 1)
    }
    if !self.nextPageToken.isEmpty {
      try visitor.visitSingularStringField(value: self.nextPageToken, fieldNumber: 2)
    }
    if !self.executionErrors.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.executionErrors, fieldNumber: 3)
    }
    if !self.unit.isEmpty {
      try visitor.visitSingularStringField(value: self.unit, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Monitoring_V3_ListTimeSeriesResponse, rhs: Google_Monitoring_V3_ListTimeSeriesResponse) -> Bool {
    if lhs.timeSeries != rhs.timeSeries {return false}
    if lhs.nextPageToken != rhs.nextPageToken {return false}
    if lhs.executionErrors != rhs.executionErrors {return false}
    if lhs.unit != rhs.unit {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Monitoring_V3_CreateTimeSeriesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".CreateTimeSeriesRequest"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{2}time_series\0\u{1}name\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.timeSeries) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.name) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.timeSeries.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.timeSeries, fieldNumber: 2)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Monitoring_V3_CreateTimeSeriesRequest, rhs: Google_Monitoring_V3_CreateTimeSeriesRequest) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.timeSeries != rhs.timeSeries {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Monitoring_V3_CreateTimeSeriesError: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".CreateTimeSeriesError"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}time_series\0\u{1}status\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._timeSeries) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._status) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._timeSeries {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._status {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Monitoring_V3_CreateTimeSeriesError, rhs: Google_Monitoring_V3_CreateTimeSeriesError) -> Bool {
    if lhs._timeSeries != rhs._timeSeries {return false}
    if lhs._status != rhs._status {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Monitoring_V3_CreateTimeSeriesSummary: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".CreateTimeSeriesSummary"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}total_point_count\0\u{3}success_point_count\0\u{1}errors\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.totalPointCount) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.successPointCount) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.errors) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.totalPointCount != 0 {
      try visitor.visitSingularInt32Field(value: self.totalPointCount, fieldNumber: 1)
    }
    if self.successPointCount != 0 {
      try visitor.visitSingularInt32Field(value: self.successPointCount, fieldNumber: 2)
    }
    if !self.errors.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.errors, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Monitoring_V3_CreateTimeSeriesSummary, rhs: Google_Monitoring_V3_CreateTimeSeriesSummary) -> Bool {
    if lhs.totalPointCount != rhs.totalPointCount {return false}
    if lhs.successPointCount != rhs.successPointCount {return false}
    if lhs.errors != rhs.errors {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Monitoring_V3_CreateTimeSeriesSummary.Error: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = Google_Monitoring_V3_CreateTimeSeriesSummary.protoMessageName + ".Error"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}status\0\u{3}point_count\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._status) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.pointCount) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._status {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.pointCount != 0 {
      try visitor.visitSingularInt32Field(value: self.pointCount, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Monitoring_V3_CreateTimeSeriesSummary.Error, rhs: Google_Monitoring_V3_CreateTimeSeriesSummary.Error) -> Bool {
    if lhs._status != rhs._status {return false}
    if lhs.pointCount != rhs.pointCount {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Monitoring_V3_QueryTimeSeriesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".QueryTimeSeriesRequest"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{2}\u{6}query\0\u{4}\u{2}page_size\0\u{3}page_token\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.query) }()
      case 9: try { try decoder.decodeSingularInt32Field(value: &self.pageSize) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.pageToken) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.query.isEmpty {
      try visitor.visitSingularStringField(value: self.query, fieldNumber: 7)
    }
    if self.pageSize != 0 {
      try visitor.visitSingularInt32Field(value: self.pageSize, fieldNumber: 9)
    }
    if !self.pageToken.isEmpty {
      try visitor.visitSingularStringField(value: self.pageToken, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Monitoring_V3_QueryTimeSeriesRequest, rhs: Google_Monitoring_V3_QueryTimeSeriesRequest) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.query != rhs.query {return false}
    if lhs.pageSize != rhs.pageSize {return false}
    if lhs.pageToken != rhs.pageToken {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Monitoring_V3_QueryTimeSeriesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".QueryTimeSeriesResponse"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{8}time_series_descriptor\0\u{3}time_series_data\0\u{3}next_page_token\0\u{3}partial_errors\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 8: try { try decoder.decodeSingularMessageField(value: &self._timeSeriesDescriptor) }()
      case 9: try { try decoder.decodeRepeatedMessageField(value: &self.timeSeriesData) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.nextPageToken) }()
      case 11: try { try decoder.decodeRepeatedMessageField(value: &self.partialErrors) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._timeSeriesDescriptor {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    if !self.timeSeriesData.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.timeSeriesData, fieldNumber: 9)
    }
    if !self.nextPageToken.isEmpty {
      try visitor.visitSingularStringField(value: self.nextPageToken, fieldNumber: 10)
    }
    if !self.partialErrors.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.partialErrors, fieldNumber: 11)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Monitoring_V3_QueryTimeSeriesResponse, rhs: Google_Monitoring_V3_QueryTimeSeriesResponse) -> Bool {
    if lhs._timeSeriesDescriptor != rhs._timeSeriesDescriptor {return false}
    if lhs.timeSeriesData != rhs.timeSeriesData {return false}
    if lhs.nextPageToken != rhs.nextPageToken {return false}
    if lhs.partialErrors != rhs.partialErrors {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Monitoring_V3_QueryErrorList: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".QueryErrorList"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}errors\0\u{3}error_summary\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.errors) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.errorSummary) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.errors.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.errors, fieldNumber: 1)
    }
    if !self.errorSummary.isEmpty {
      try visitor.visitSingularStringField(value: self.errorSummary, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Monitoring_V3_QueryErrorList, rhs: Google_Monitoring_V3_QueryErrorList) -> Bool {
    if lhs.errors != rhs.errors {return false}
    if lhs.errorSummary != rhs.errorSummary {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
